# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
# Copyright (C) 2025 Linaro Ltd.

obj-y	= cpu.o
obj-y	+= cp15.o
obj-y	+= cache.o
obj-y	+= lowlevel.o
obj-y	+= mpp.o
